### ISSUE TITLE
Readme's performance demo is broken

### ISSUE THREAD

**Issue by MarcoWorms** [ethereum/moon-lang#11]
In `readme.md`, the sentence bellow has a broken link:

------
- **Fast:** when compiled to JS, it beats popular libs by [a large margin](moon-demo/demo-performance.js).
------

**Comment by VictorTaelin** [comment]
Moon is going through a major update right now, by the morning everything should be normalized.

**Comment by MarcoWorms** [comment]
It works now :tada:
