### ISSUE TITLE
Moon module system.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#15]
* Obtaining packages trough hash string seems a bit cumbersome to me. How do I find hash code of my function, will I have to open browser and search it? What if there is a typo in hash and its going to fetch a completely different function - such a bug might be hard to spot?

* The `get` function is currently the only dynamic function in core ( it can output expressions with different types ). Do we really want this function? It will cause problems if we would like to migrate to types in the future. And it will also mess up some static optimizations.

**Comment by VictorTaelin** [comment]
1. You use `Moon.cid` to find the hash of your function. See how the modules currently on base are represented. In a future with proper editor support that will be even simpler, and with ENS or similar we may have actual names. Also, it will never happen that you import a different function because of a typo. If there is a typo, it will be undefined. Finally, I think hash addressed imports is one of the best things about Moon, since it guarantees that no code ever breaks, and you get hosting for free.

2. `get` isn't "dynamic". Consider it of type `get : ∀ (t : String -> Type) -> Map t -> (key : String) -> (t key)`. As long as you use it correctly (i.e., don't set the same key to different types, I guess), your code will be portable to the typed version fine (at least not harder than porting the rest of the code already will be).

**Comment by AnthonyJacob** [comment]
1. I think I will have to see this in action.

2. `get : ∀ (t : String -> Type) -> Map t -> (key : String) -> (t key)`
Oh cool, isn't that dependant typing? I like it.

By the way does it make sense to explicitly annotate variables with forall? It has never happen to me, that I had ran out of letters, so I think every lower case type variable could be prefixed with `∀` automatically.

**Comment by VictorTaelin** [comment]
Okay! But I don't understand the last question...

**Comment by AnthonyJacob** [comment]
I probably have a wrong understanding of `∀`... What does it actually do? How is for example this `get : ∀ (t : String -> Type) -> Map t -> ∀ (key : String) -> (t key)` function different? 

Does it mean that whenever I use `key` in a type signature anywhere inside `get` function, it will be of type `key : String` ?

**Comment by VictorTaelin** [comment]
It means that, for all functions `t` of `String -> Type`, the type of `get` is `Map t -> (key : String) -> t key`. So, for simplicity, let's pick a concrete `t`:

```idris
t : String -> Type
t x = Maybe Int
```

In other works, `t` receives a `String` and always returns `Int`. When we select that `t` specifically, `get` becomes of type:

```
Map (const Int) -> String -> Maybe Int
```

That type is equivalent to Haskell's `Data.Map.lookup` for the `Data.Map String Int` type! So we could compile to it, for example. Now, let's pick another concrete `t`:

```idris
t : String -> Type
t "name" = String
t "age" = Int
t x = ⊥
```

With that specific `t`, `get` becomes of type:

```idris
Map (t => case t of {"name" -> String; "age" -> Int; _ -> ⊥})
-> (key : String) 
-> (case key of {"name" -> String; "age" -> Int; _ -> ⊥})
```

A bit abstract, so, for even more simplicity, let's apply `get` to concrete strings:

The type of `(obj => (get obj "name"))` is:

```idris
Map t -> String
```

And the type of `(obj => (get obj "age"))` is:

```idris
Map t -> Int
```

Do you see where I'm going? With this specific choice of `t`, maps become equivalent to C records! Specifically, one with a field `name : String` and a field `age : Int`, and `get obj "name"` becomes equivalent to `obj.name` (using C syntax), and can be compiled as such. The point of the type above is that a parametric `t` gives us flexibility to use Moon maps as either records or actual maps, and only later specify exactly what we meant when we migrate to a typed version. As long as your program actually makes sense (i.e., you don't use a map with different types for the same field), you'll probably be able to formalize it fine.

**Comment by AnthonyJacob** [comment]
Yes, I get it, but does it make sense to have forall in the following signature `foo : ∀(key : String)`? Or does it make sense only for type signatures that contain `Type` like the `t` function does?

Also - is `t : String -> Type` equivalent to `t : String -> a` ?

**Comment by VictorTaelin** [comment]
@AnthonyJacob no, `t : String -> Type` is a function from Strings to types, and `String -> a` is a function from Strings to `a` (which is parametric, so you could chose `Type`, but you could also chose `String`, on which case `t` would be just a `String -> String` function).

You mean `∀` as in the symbol? It is not necessary. You only need to be able to differ forall from lambdas. You could make that difference by using `->` for types and `=>` for functions. Then `∀` can be removed from forall (like we don't need to type `λ` for lambdas).
