### ISSUE TITLE
Lambda calculus with named arguments.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#16]
I have stumbled upon [this paper](http://scg.unibe.ch/archive/oosc/PDF/Dami95aLambdaN.pdf) which explores the idea of extending lambda calculus with named arguments:

``` javascript
pair = fst => snd => fun =>
    (fun item1= fst  item2= snd)
triplet = fst => snd => thd => fun =>
    (fun item1= fst  item2= snd  item3= thd)
```

the cool thing about this, is that every function that works with `pair` will also work with `triplet`

``` javascript
snd = item2 => item2

(pair fst= 2017  snd= "Hello") snd // returns "Hello"
(triplet fst= 2017  snd= "Hello"  thd= "World") snd // also returns "Hello"
```

What do you think, would it be a worthwhile to explore this area? It looks like its going to work *really well* with partiall application and **scott encoded data structures**!

**Comment by VictorTaelin** [comment]
Can that be done without affecting the core, just as an editor thing for human programmers to use? If so, that sounds like a good addition, why not? Reminds extensible records. I might take a look on the paper later on.

**Comment by AnthonyJacob** [comment]
It might be possible, but they have chosen a different approach. Their core looks like :
```haskell
Term = Lam Term               -- abstraction
     | Var Name Number        -- variable
     | Bind Name Term         -- bind operation - the substitution part of beta reduction
     | Close Term             -- close operation - the lambda reduction part of beta reduction
```

But it could also be defined as
```haskell
Term = App Term [(Name, Term)]
     | Lam Term
     | Var Name Number
```

**Comment by AnthonyJacob** [comment]
Basically, lambda abstraction would be allowed to have multiple arguments: 

``` javascript
triplet = fst => snd => thd => fun =>
    (fun (i1= fst  i2= snd  i3= thd))    // syntax for applying multiple arguments

add2 = i1  i2 => 
    (add a= i1  b= i2)

add3 = i1  i2  i3 =>
    (add a= (add a= i1 b= i2)  b= i3)

t = (triplet fst= 1  snd= 2  thd= 3)

(t fun= add2)     // returns 3
(t fun= add3)     // return 6
```

Or no arguments at all:

```javascript
undefined = => undefined
error = message => => error message
```

**Comment by VictorTaelin** [comment]
But there is absolutely nothing stopping us to make a two-way map between their core and Moon, right? I think the perfect future would have idealistic Moon (as I described on the other thread) as the universal bytecode, and many satellite languages with different syntaxes compiling to and from it. On the browser you should be able to pick a syntax, be it Python or Haskell, and see only what you want. This could be one of those satellite languages.

**Comment by AnthonyJacob** [comment]
The problem is, you lose the names after you convert their core into moon core and you will never be able to retrieve it back. 

So although you will be able to run the language trough moon, you won't be able to use it as a lambda calculus JSON.

**Comment by VictorTaelin** [comment]
Not if you annotate the names with `((x => y => y) "name" lambda)`...

**Comment by AnthonyJacob** [comment]
I thought moon will discard this information, because it is stored (in the ideal case) as a normal form.

**Comment by AnthonyJacob** [comment]
And how do you compile the `Close` constructor into moon with the possibility to recover it back?

**Comment by VictorTaelin** [comment]
In the absolute worst case you can compile everything to an ADT and use HOAS...

**Comment by AnthonyJacob** [comment]
That is an interesting idea.

Anyway, I have thought about it a little bit and I have come to following conclusion:

1. What enables sub typing is the split of beta reduction into two separate concepts (`Bind` & `Close`). 

* But now comes the question, what does sub typing actually give us? Are there some sorts of algorithms that are much more easy to express with sub typing? 

I would very much know answer to this question, since OOP is very popular and is built around sub typing, yet it seems Haskell was able to get away without it. But it definitely seems like a powerful concept since it allows us to express immutable fixed size arrays without adding a special constructor for them...

* If the answer is yes, then we have to ask another question, is that feature so important to include it in the moon language itself?

2. Named function parameters is what makes sub typing really shine.

* Although it does not require new constructors, you have to keep - potentially useless - additional information in several constructors.

* Implementation of Bind is not trivial and its evaluation will be probably slower by some constant factor.

**Comment by VictorTaelin** [comment]
(BTW, I really think this is very promising in terms of usability and definitely fits somewhere, I just didn't have a lot of time to look at it to comment meaningfully.)

**Comment by AnthonyJacob** [comment]
A little neat thing you can do with `Bind` and `Close` without the need for named parameters:

```haskell
iden = x => x
skip = _ => iden
arg1 = iden
arg2 = skip arg1
arg3 = skip arg2
arg4 = skip arg3

True = arg1
False = arg2

Nothing = arg1
Just = a => arg2

Left = a => arg1
Right = a => arg2

Nil = arg 1
Cons = a => as => (arg2 a b)
```

**Comment by AnthonyJacob** [comment]
Never mind, it would not actually work. It would require a different notation with respect to `Close`.

For example (`!` closes lambda abstraction):
```haskell
foo = x !=> a => b !=> (add x (add a b))
((foo 1 2)! 3 4 5)! -- returns 8
(((_ => foo) 1 2)! 3 4 5)! -- return 9
```

That already feels a little too complicated.

**Comment by AnthonyJacob** [comment]
Oh, and splitting `App` into `Bind` and `Close` also enables: optional arguments, variadic functions.

**Comment by Kesanov** [comment]
So I think code reuse is extremely important for low level languages, because it reduces binaries size therefore compilation time.

Even more powerful is the concept of arrays or hashmaps (one can be used to implement the other) yet it  does not look like lambda calculus is able to express them.

**Comment by VictorTaelin** [comment]
The λ-calculus can express hashmaps fine, why couldn't it? See Haskell's Data.Map for example.

**Comment by Kesanov** [comment]
Oops , of course it can. I did not realize trees require only fixed size data structures.

**Comment by Kesanov** [comment]
I think the feature can be to some extent simulated with the following syntax sugar

```haskell
person = 
  firstName => lastName => age => address => phone => fun => 
    (fun firstName lastName age address phone)

fstName = 0 ^ firstName => 5 ^ firstName
lstName = 1 ^ lastName => 5 ^ lastName
whlName = 0 ^ a => 1 ^ b => 5 ^ (concat a b)
```

will be compiled into

```haskell
fstName = firstName => _ => _ => _  => _ => firstName
lstName = _ => lastName => _ => _  => _ => lastName
whlName = a => b => _ => _ => _ =>  (concat a b)
