### ISSUE TITLE
How to compile following expressions to moon?

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#17]
It seems like `Let` expressions do not play well with the idea of keeping AST:

```haskell
-- applies function to every element of list
map _ [] = []
map f (x:xs)= f x : f xs
```
compiles to
```haskell
map = f => list => (list
    Nil
    x => xs => (Cons (f x) (map f xs)))
```
but what happens if I want to keep the comment?
```haskell
comment = msg => expr => expr
(comment "applies function to every element of list"
map = ... )
```
passing `Let` expression to function does not make sense, what shall I do?

**Comment by VictorTaelin** [comment]
Interesting question, but I'd say just 

```javascript
comment = msg => expr => expr
map = (comment "applies ..." (f => list => (list Nil x => xs => (Cons (f x) (map f xs))))
...
```

It is not ambiguous because what else could that mean?

**Comment by AnthonyJacob** [comment]
What about this though:

```haskell
data List a = Nil | Cons a (List a)
```
will compile to
```haskell
Nil  = a => _  => a
Cons = a => as => _ => f => (f a as)
```
but then again, I would like to include the `data List a`, but
```haskell
data = type => x => x
Nil  = (data "List a" a => _  => a)
Cons = (data "List a" a => as => _ => f => (f a as))
```
is not efficient at all. Just imagine you have 40 constructors!

**Comment by AnthonyJacob** [comment]
By the way, does your binary format keep argument names or does it use De Bruijn index?

**Comment by Kesanov** [comment]
So I would say something like

```haskell
data = "List a"
Nil  = a => _  => a
Cons = a => as => _ => f => (f a as)
```

should be sufficient.

**Comment by VictorTaelin** [comment]
O like the idea of having Haskell-like adts, though:

```
List = "data List a = Cons a (List a) | Nil"
```

Which would return `{Cons: ..., Nil: ..., fold: ..., equals: ..., show: ..., map: ..., ...}`
