### ISSUE TITLE
Feature: Space indentation makes parentheses optional.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#3]
I am an advocate of Occam's razor and LISP languages are usually **glaring** example of unnecessary duplication of work.

Why do you need to wrap your code in parentheses, when compiler can do it for you?

``` 
(andThen '(1 2 3)
   (map (add 1))
   (filter (lt 3))
   (take 10))
```

Do you see the pattern? 

1. Eery line starts with `(`
2. **If** the following line has the same indentation as the current one
        - **then** place `)` at the end of line.
        - **else** place `)` at the end of the **last** line with same indentation.

Thats it. Homoiconity is preserved and we get pleasant looking (even to javascript folks) expression.

``` haskell
andThen '(1 2 3)
   map (add 1)
   filter (lt 3)
   take 10
```

**Comment by VictorTaelin** [comment]
I agree the current syntax isn't great, but it was the best I could do in a single pass while not making the parser need to look back (remember, parsing needs to be fast). I'm not sure one can implement what you want without that. Also, I actively avoided line breaks affecting the code. Soon, though, the syntax will be separated from the core, allowing you to design your own improved syntax!

**Comment by AnthonyJacob** [comment]
BTW The following code from documentation uses space indentation?  

```
run:
    | x: <get
      inc>
      inc>
      inc>
      y: <get
      dec>
      dec>
      z: <get
      (ret [x y z])
  (run 0)
```

**Comment by AnthonyJacob** [comment]
You definitely do not need to look back, since you only need to know the indentation of each block you are in. So while parsing you only need to keep a state as `[Int]` where its length is number of nested blocks.

Also, why do you try to avoid line breaks to be part of parser process?

**Comment by VictorTaelin** [comment]
@AnthonyJacob because space indentation *forces* you to use line breaks! Sometimes you want to have the option to leave everything in a single line, but you can't if the parser forces you to indent. Many parenthesis can be avoided without space indentation. That is the case for that snippet above: there is no space indentation, yet it looks like there it is. You can collapse that all to a single line and it still works. Take, for example, this `mergeSort` implementation:

```haskell
mergeSort: lis.
  
  Cons: head. tail.
    cons. nil. (cons head tail)

  Nil: cons. nil.
    nil

  toSList: array.
    (arrayToList array Cons Nil)

  fromSList: lis.
    toList: lis. cons. nil.
      go: go@ lis. (lis h. t. (cons h (go t)) nil)
      (go lis)
    (listToArray (toList lis))

  reverse: xs. 
    go: go@ r. lis.
      case_xs: x. xs. (go (Cons x r) xs)
      case_nil: r
      (lis case_xs case_nil)
    (go Nil xs)

  merge: a. b.
    go: go@ r. aas. bbs.
      case_as_bs: a. as. b. bs.
        (if (gtn a b)
          (go (Cons b r) (Cons a as) bs)
          (go (Cons a r) as (Cons b bs)))
      case_as_nil: a. as.
        (go (Cons a r) as Nil)
      case_nil_bs: b. bs.
        (go (Cons b r) Nil bs)
      case_nil_nil:
        (reverse r)
      (aas a. as.
        (bbs (case_as_bs a as) (case_as_nil a as))
        (bbs case_nil_bs case_nil_nil))

    (go Nil a b)

  split: split@ d. lis.
    case_0: Lazy.
      case_xs: x. xs. t. (t (Cons x Nil) xs)
      case_nil: t. (t (Cons 0 Nil) Nil)
      (lis case_xs case_nil)
    case_N: Lazy.
      (split (sub d 1) lis lef. lis.
      (split (sub d 1) lis rig. lis.
      t. (t (merge lef rig) lis)))
    (if (eql d 0) (case_0 x.x) (case_N x.x))

  depth: (flr (log 2 (get lis "length")))

  (fromSList (split depth (toSList lis) res. lis. res))

(mergeSort [1 8 3 5 2 6 7 4])
```

Most of the ugly parenthesis can be avoided. There are some parenthesis here, but it is nowhere near the Lisp `()` hell... and probably the not the biggest issue I'm worried about right now...

**Comment by AnthonyJacob** [comment]
I think you misunderstood me. I wanted space indentation to be optional, so for example following code: 

```
add a b
(add a b)
````

Would be legit - the first line does not use parentheses so compiler adds them, the second already uses parentheses...

But since moon tries to be like assembly I don't think it is important.
