### ISSUE TITLE
Bang notation and argument order.

### ISSUE THREAD

**Issue by Kesanov** [ethereum/moon-lang#30]
I have been playing a little bit with bang notation and I have found it plays pretty poorly with current argument order (**V**erb **F**irst **S**ubject **L**ast).

```haskell 
-- `flip` wouldn't work, but `flip n` could, it is rather verbose though
|(a =< a => flatMap a as
  b =< b => flatMap b bs
  c =< c => flatMap c cs
  wrap (tuple 3 a b c))
```

With **SFVL** on the other hand it feels very natural.

```haskell
|(a =< flatMap as
  b =< flatMap bs
  c =< flatMap cs
  wrap (tuple 3 a b c))
```

But then we could not write 
```haskell
transformation = list => (flatMap doC (flatMap doB (flatMap doA list)))
```
We obviously need some way to flip arguments in a pleasant way, so I thought we might provide syntax to turn any function to `infixl`.

```haskell
transformation = list =>
  (list
    .flatMap doA
    .flatMap doB
    .flatMap doC)
```
and we could represent this syntax as `. = x=>x (. flatMap doC (. flatMap doB (. flatMap doA list)))`, so we can later deserialize it back.

I am still wondering whether this solution isn't too complicated... What do you think?

**Comment by VictorTaelin** [comment]
I'm not sure if I get the situation of the first example, but I like the idea. I might implement it if I add `+`, `*`. etc. as operators, looks like the code would be the same. Only problem of those is precedence without needing to look back.

**Comment by Kesanov** [comment]
What do you mean by *"without needing to look back."*? With recursion it should be pretty easy to parse infix operators no? You just put the term that occurred before operator into accumulator.

**Comment by Josef-Vonasek** [comment]
Well, I have come up with something better: **the rule of penultimate - ultimate**.

In english : You always should put the verb as the last but not least argument and subject as the last argument (or the other way around, it does not matter).

Example:
```haskell
fold =
  b =>
  fun => --verb
  list => --subject
    ...
```

Then we just need syntactic sugar for `flip`.

Example:
```haskell
foo a 'b c == flip (foo a) b c == foo a c b
```

Then it is easy to chain functions:

```haskell
flatMap fun list = flatten (map fun list)

-- monadic code is easy
flatMap '[1,2] ( a =>
flatMap '[3,4] ( b => 
flatMap '[5] ( c =>
wrap (a,b,c) ))) -- [(1,3,5), (1,4,5), (2,3,5), (2,4,5)]

-- and applying bunch of transformation also
fold b foo (flatMap bar (reverse (map baz list)))
```

**Comment by Kesanov** [comment]
I guess shorthand syntax for anonymous functions would be in the end the easiest solution: 
```haskell
(a => b => foo a x b) == (foo _ x _)
```
