### ISSUE TITLE
Make parentheses truly mathematical.

### ISSUE THREAD

**Issue by Kesanov** [ethereum/moon-lang#35]
Currently parentheses always mean application, but it would be so much better, if they would behave like mathematical ones. Then we would gain:

**1. Let without parentheses**
```haskell
( foo = something1 a b c d
  bar = something2 e f g
  baz = something3 v w x y
) foo bar baz
```

**2. Nice monadic syntax**
```haskell
askPowerLevel = loop@ lazy =>
  do "prompt" "What is your power level?"  power =>
    if (gtn (stn power) 9000)
    ( do "print" "No, it is not."  _ =>
      loop 0 )
    ( do "print" "Ah, that's cute!"  _ =>
      do "stop" )
```

**Comment by VictorTaelin** [comment]
Parenthesis are how they are now because otherwise we'd have some ambiguities in the parser IIRC. I think doing anything different at this point would be a gigantic refactoring work, or do you have something way to implement it in mind?
