### ISSUE TITLE
Concatenative lambda calculus.

### ISSUE THREAD

**Issue by Kesanov** [ethereum/moon-lang#37]
I have recently read [Why Concatenative Programming Matters](http://evincarofautumn.blogspot.cz/2012/02/why-concatenative-programming-matters.html) and got very interested in it. The advantages are:

* You can get rid of `Lambda` and `Var` for MUCH smaller price, than you could in lambda calculus.
* Functions **can** return multiple values. Not just tuples.
* *"Parallel compiler is a plain old map-reduce."*
* It is very efficient (stack based).
* It is well researched topic. JVM and CPython bytecode are build on top of concatenative programming.
* Concise, point free, less parentheses (=> small binary size).

The only disadvantage is, some functions are harder to express (but that is a real minority) which can be solved by syntactic sugar (or introducing `,` - post bellow) and ultimately we should not care about it, since moon is exchange format in the first place.

**Comment by Josef-Vonasek** [comment]
Another very interesting article:[Writing a Concatenative Programming Language: Introduction](https://suhr.github.io/wcpl/intro.html)

**Comment by Kesanov** [comment]
#### So to sum it up, I have come to following conclusion:

* Replacing `Apply` with `Compose` gives us **linear logic**. 
  *In other words we need **no garbage collection**.*
* Replacing `Lambda` and `Var` with **combinators** does not destroy readability of the language.* After all, composition promotes point free style. 
  *In other words **parsing is trivial** and we do not need to implement **graph reduction**.*
* Static typing is more important than in classical lambda calculus, because it prevents memory related bugs.*
* Domain Specific Language is very easy to express.


----

* As an evidence, most concatenative languages use combinators. Something that not even GHC Core does (which is an IR, so nobody writes it anyway).
* For example `undefined ([end] 2 val 1 val) foo map == undefined ([end] 2 foo val 1 foo val)` `foo` will try to evaluate `undefined` unless we constrain `foo` to take exactly one argument at the type level.
* We do not actually need full static typing to ensure memory safety. Knowing arities of all functions is enough (they can be easily inferred).

**Comment by Kesanov** [comment]
If you are still interested, you can get taste of concatenative programming in this [factor tutorial](https://andreaferretti.github.io/factor-tutorial/). I recommend downloading the language, it has only 50MB in size and contains very nice REPL with builtin documentation.

**Comment by VictorTaelin** [comment]
I don't think combinator-based languages are expressive enough, look for example how Epigram switched from supercombinators to graph reduction (IIRC). I do think it might be better than the λ-calculus (I'm convinced lambdas are harmful at this point), but not better than interaction combinators, which is what I'm aiming for the next iterations.

**Comment by Kesanov** [comment]
You only address my second point though. We can still replace Apply with `Compose` and keep `Lambda` and `Var` around.

**Comment by Kesanov** [comment]
Specifically, I think it might be interesting to use **interaction nets** to run this calculus:

```haskell
data Trm
  = Com Trm Trm  -- compose  fun fun
  | Lam Trm      -- lambda   body
  | Var Trm      -- variable index
```

Sadly there are no papers on this topic, so we would need to come up with our own rewrite rules and I have no idea how to do that...

**Comment by Kesanov** [comment]
So I have came to conclusion that 

`concatenative calculus + higher order function` = `lambda calculus where functions can return multiple values`

That is rather disappointing (and the reason why I am closing this issue).
