### ISSUE TITLE
Records as basic data structure.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#5]
Have you thought about using **records** as basic data structure?.

Showcase:

* function call
`(add 1 2)`

* dynamically sized data structure ~ list, map, set, vector, etc
`[1 (add 1 2)]`

* tuple is a record with fields `1`, `2` .. `n`
`{1 (add 1 2)}`

* record with fields `a`, `b`
`{a=1 b=(add 1 2)}`

* field access
```
{a=1}.a
(.a {a=1}) -- .a is just a function
```

* simple module system 
```
echo {add  = (a. b. (add a b))} > ./foo.moon
echo {main = (foo.add 1 2)}     > ./bar.moon
run-moon ./bar.moon
3
```
* `let in` expression
```
(let {a=1} (add a 1))
```
* to keep some methods private you just use `let`
 ./foo.moon
```
(let 
  {inc  = (a. (add a 1))}
  {main = (inc 10)})
```

```
echo {main = (foo.inc 1)}     > ./bar.moon
run-moon ./bar.moon

error: record `foo` does not have field `inc`
```

**Comment by AnthonyJacob** [comment]
As you see, although records are indeed a very simple data structure, they extremely improve the expressiveness of language.

**Comment by VictorTaelin** [comment]
That's already part of Moon... it is called map. It is expressed as `{"field1": value1, "field2": value2}`. An array is just syntax sugar for a map with fields `0`, `1`, ... `n`, and `length`. Field access is `(get map "field")`. With @Pyrolistical's syntax, you can use the dot notation.

**Comment by VictorTaelin** [comment]
Note that, despite it being part of Moon, it doesn't actually increase it expressivity. Maps/records can be expressed with λ-encoded datatypes on the calculus, so there is no need to have it. It will possibly be removed in a future.

**Comment by AnthonyJacob** [comment]
> Note that, despite it being part of Moon, it doesn't actually increase it expressivity. 

Oh well, I meant convenience then.

**Comment by VictorTaelin** [comment]
Hmmm, but I'm not sure I understand... what you described is already part of the lang so I don't get it (?)

**Comment by AnthonyJacob** [comment]
You need to make a simple tutorial really, one page with few examples is not enough. I would not mind doing it myself, but currently I am fighting with nixos installation.

**Comment by AnthonyJacob** [comment]
> Maps/records can be expressed with λ-encoded datatypes on the calculus, so there is no need to have it. It will possibly be removed in a future.

Oh I see, so moon is trying to be something similar to assembly, the less primitives it has the better.

**Comment by VictorTaelin** [comment]
Exactly! It is sort of like a functional assembly. The philosophy is: if a feature can be implemented **on top** of Moon, it should not be a primitive. The reason for that is to make it as simple as possible to implement Moon in different environments. That way, Moon code achieves some sort of universality, like what Java attempted to do, but from the other way around: instead of making a huge VM that runs everywhere, we build a language so simple "we can compile it to anywhere". 

The point of using a functional core rather than a small ASM-like language is that it preserves the logical structure of a program. That has many benefits. For one, it is possible to recover the original, high-level human-readable syntax of a complex Moon application from the bytecode! This allows, for example, the user of a browser to recover an high-level code from any application, so any app made on Moon is easily forkable. If we used WASM, the user wouldn't be able to do so, the best we could do is make the ASM more readable, but that is hard.

**Comment by VictorTaelin** [comment]
I'm sorry about the tutorial, things aren't friendly enough yet, but for now I'm too busy with making a browser for Moon apps...

**Comment by AnthonyJacob** [comment]
>  For one, it is possible to recover the original, high-level human-readable syntax of a complex Moon application from the bytecode! 

Are you sure? What if I compile something that cannot be expressed in moon directly ? E.G pattern matching compiled into moon as some `if` hackery. How can you recover it back?

>  the best we could do is make the ASM more readable, but that is hard

I am all up for that. I hate GHC core because it is so unreadable. That's why I though moon could be built on top of records similar to LISP which is built on top of lists, but you really need **concise field accessor syntax** like `.age` to be readable! Would it complicate the language so much?

**Comment by AnthonyJacob** [comment]
For example this is the beginning of haskell Prelude rewritten in moon, with 

1. records 
2. pattern matching 
3. syntactic sugar for lambdas

Notice how you can nicely simulate sum types with records !

``` haskell
(
-- person : (name : String, age : Int)
person = (name = "john", age = 27),

-- id : a -> a
id = a. a,

-- const : a -> b -> a
const a _ = a,

-- >> : (a -> b) -> (b -> c) -> (a -> c)
>> f1 f2 a = f2 (f1 a),

-- |> : a -> (a -> b) -> b
|> a f = f a,

-- flip : (a -> b -> c) -> (b -> a -> c)
flip f a b = f b a,

-- type Bool = (true : ()) | (false : ())
-- not : Bool -> Bool
not (true) = (false = ()),
not (false) = (true = ()),

-- type Either a b = (ok : a) | (err : b)
-- either : (a -> c) -> (b -> c) -> Either a b -> c
either f _ (ok) = f ok,
either _ f (err) = f2 err,
)
```

**Comment by AnthonyJacob** [comment]
`case of` can be implemented as `match a (case) = case a` and then used like this : 
```haskell
main = match (person = (name = "john", age = 27)) (
  case (person = ("john", _)) = "Hello John",
  case _ = "Sorry, I don't know you",
)
```

**Comment by AnthonyJacob** [comment]
Anyway I agree that pattern matching should be implemented by the means of scott encoding.

**Comment by VictorTaelin** [comment]
Woops, I missed the last two posts, but yes, I think scott encodings are the way to go to encode any ADT that you can express in Haskell.

**Comment by AnthonyJacob** [comment]
I see you have removed the quotes from map syntax 👍.

Why does moon-core contain `Let` constructor when it also has `Map`? Does not `Map` provide all functionality that `Let` does and more?
