### ISSUE TITLE
Feature : Extractors.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#7]
Extractors look like a really nice feature, for illustration:
```
match [1] ([x]. x) ([]. 0) -- returns  1
match [ ] ([x]. x) ([]. 0) -- returns  0
```
You can define your own if you want:
```
pattern (Some x <- [x])
pattern (None   <- [ ])
match (Some x) ([x]. x) ([]. 0) -- returns  1
match  None    ([x]. x) ([]. 0) -- returns  0
```

Naturally it can be implemented on top of moon already, but if I would serialize my higher language (with extractors) into moon (that does not have them) and then deserialize it back I am going to lose all my abstraction.

**Comment by VictorTaelin** [comment]
What exactly would you lose? Could you be more specific? AFAIK scott-encodings allow you to do exactly that, have you researched them? For example, let's use a Pythonist language:

```
def sum(pair):
  (a,b) = pair
  return a + b

print sum([1,2])
```

Compiles to: 

```
sum: pair.
  (pair a. b.
    (add a b))

(sum p.(p 1 2))
```

Which correctly outputs `3`. It can also be desugared back to Python by replacing `p. (p x y)` with `(x, y)` and `(f x. y. t)` by `(x, y) = f <newline> t`. From that you can elaborate to recursive pattern matchings and more complex expressions...

**Comment by VictorTaelin** [comment]
Your example, by the way:

```
match (Some 1) ([x]. x) ([]. 0) -- returns  1
match  None    ([x]. x) ([]. 0) -- returns  0
```

Compiles to:

```
Some: value. some. none. (some value)
None: some. none. none
match: value. caseSome. caseNone. (value caseSome caseNone)

[
  (match (Some 1) (x. x) 0) -- returns 1
  (match  None    (x. x) 0) -- returns 0
]
```

**Comment by AnthonyJacob** [comment]
Oh, I have totally forgot about scott encoding to be honest. What bugs me tho, is how do you encode sumtype like `Etiher a b = Left a | Right b` since Left and Right have same number of arguments!
